# Generated by Django 2.2.11 on 2020-03-26 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=70)),
                ('delivery', models.CharField(choices=[('quick', 'Quick'), ('normal', 'Normal')], max_length=20)),
                ('mobile', models.PositiveIntegerField()),
                ('requirements', models.TextField(blank=True, max_length=100)),
                ('total_price', models.PositiveIntegerField()),
                ('ordered', models.BooleanField(default=False)),
                ('payment', models.CharField(choices=[('card', 'CreditCard'), ('mobile', 'Mobile'), ('others', 'Others')], max_length=20)),
                ('agreed', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='kurly.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=30)),
                ('package', models.CharField(max_length=30)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.TextField(max_length=255)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveSmallIntegerField(default=99)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kurly.Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('option', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='kurly.Order')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kurly.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='kurly.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='https://wpsios-s3.s3.ap-northeast-2.amazonaws.com/media/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kurly.Product')),
            ],
        ),
    ]
