# Generated by Django 2.2.11 on 2020-03-31 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=30)),
                ('delivery', models.CharField(choices=[('quick', '샛별배송'), ('normal', '일반배송')], max_length=20)),
                ('mobile', models.PositiveIntegerField()),
                ('requirements', models.TextField(blank=True, max_length=100)),
                ('total_price', models.PositiveIntegerField()),
                ('is_ordered', models.BooleanField(default=False)),
                ('ordered_at', models.DateTimeField()),
                ('payment', models.CharField(choices=[('card', '카드결제'), ('mobile', '휴대폰결제'), ('others', '기타결제')], max_length=20)),
                ('payed_at', models.DateTimeField()),
                ('is_agreed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('yet', '배송준비중'), ('on', '배송중'), ('done', '배송완료')], default='yet', max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='members.Address')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='kurly.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=30)),
                ('package', models.CharField(max_length=30)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.TextField(max_length=255)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveSmallIntegerField(default=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='kurly.Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='kurly.Option')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='kurly.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='kurly.Product')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='kurly.Product'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kurly.Product')),
            ],
        ),
    ]
