# Generated by Django 2.2.11 on 2020-04-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurly', '0003_orderproduct_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['created_at'], name='kurly_order_created_973c10_idx'),
        ),
    ]
