# Generated by Django 2.2.11 on 2020-04-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurly', '0003_auto_20200406_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
