# Generated by Django 2.2.11 on 2020-04-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurly', '0004_auto_20200406_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='kurly.Option'),
        ),
    ]
