# Generated by Django 2.2.11 on 2020-03-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='token',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
