# Generated by Django 2.2.11 on 2020-03-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
