# Generated by Django 2.2.11 on 2020-04-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='token',
            field=models.CharField(blank=True, default='111111', max_length=10),
            preserve_default=False,
        ),
    ]
