# Generated by Django 2.2.11 on 2020-03-30 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_mobile_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
